package org.lemming.math;

public enum ThresholdingType {
		HUANG, INTERMODES, ISODATA, LI, MAXENTROPY, MEAN, MINERROR, MINIMUM, MOMENTS, OTSU, PERCENTILE, RENYIENTROPY, SHANBAG, TRIANGLE, YEN, MANUAL;
	}